2022-03-18 20:38:33,863 INFO    MainThread:7351 [internal.py:wandb_internal():87] W&B internal server running at pid: 7351, started at: 2022-03-18 20:38:33.862896
2022-03-18 20:38:33,865 INFO    WriterThread:7351 [datastore.py:open_for_write():77] open: /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_203832-2evcolff/run-2evcolff.wandb
2022-03-18 20:38:33,866 DEBUG   HandlerThread:7351 [handler.py:handle_request():130] handle_request: run_start
2022-03-18 20:38:33,871 DEBUG   HandlerThread:7351 [meta.py:__init__():40] meta init
2022-03-18 20:38:33,871 DEBUG   HandlerThread:7351 [meta.py:__init__():54] meta init done
2022-03-18 20:38:33,871 DEBUG   HandlerThread:7351 [meta.py:probe():214] probe
2022-03-18 20:38:33,877 DEBUG   HandlerThread:7351 [meta.py:_setup_git():204] setup git
2022-03-18 20:38:33,896 DEBUG   HandlerThread:7351 [meta.py:_setup_git():211] setup git done
2022-03-18 20:38:33,896 DEBUG   HandlerThread:7351 [meta.py:_save_pip():58] save pip
2022-03-18 20:38:33,896 DEBUG   HandlerThread:7351 [meta.py:_save_pip():72] save pip done
2022-03-18 20:38:33,896 DEBUG   HandlerThread:7351 [meta.py:_save_conda():79] save conda
2022-03-18 20:38:35,909 DEBUG   HandlerThread:7351 [meta.py:_save_conda():89] save conda done
2022-03-18 20:38:35,910 DEBUG   HandlerThread:7351 [meta.py:probe():252] probe done
2022-03-18 20:38:54,716 WARNING MainThread:7351 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-03-18 20:38:56,215 WARNING MainThread:7351 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-03-18 20:38:56,216 ERROR   MainThread:7351 [internal.py:wandb_internal():149] Internal process interrupted.
2022-03-18 20:38:56,874 INFO    SenderThread:7351 [sender.py:finish():1070] shutting down sender
2022-03-18 20:38:56,919 INFO    WriterThread:7351 [datastore.py:close():281] close: /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_203832-2evcolff/run-2evcolff.wandb
2022-03-18 20:38:56,920 INFO    HandlerThread:7351 [handler.py:finish():731] shutting down handler
2022-03-18 20:38:56,920 INFO    MainThread:7351 [internal.py:handle_exit():77] Internal process exited
