2022-03-18 22:27:37,354 INFO    MainThread:36847 [internal.py:wandb_internal():87] W&B internal server running at pid: 36847, started at: 2022-03-18 22:27:37.353966
2022-03-18 22:27:37,357 DEBUG   HandlerThread:36847 [handler.py:handle_request():130] handle_request: run_start
2022-03-18 22:27:37,357 INFO    WriterThread:36847 [datastore.py:open_for_write():77] open: /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_222736-23ccjkyr/run-23ccjkyr.wandb
2022-03-18 22:27:37,362 DEBUG   HandlerThread:36847 [meta.py:__init__():40] meta init
2022-03-18 22:27:37,362 DEBUG   HandlerThread:36847 [meta.py:__init__():54] meta init done
2022-03-18 22:27:37,362 DEBUG   HandlerThread:36847 [meta.py:probe():214] probe
2022-03-18 22:27:37,369 DEBUG   HandlerThread:36847 [meta.py:_setup_git():204] setup git
2022-03-18 22:27:37,396 DEBUG   HandlerThread:36847 [meta.py:_setup_git():211] setup git done
2022-03-18 22:27:37,397 DEBUG   HandlerThread:36847 [meta.py:_save_pip():58] save pip
2022-03-18 22:27:37,398 DEBUG   HandlerThread:36847 [meta.py:_save_pip():72] save pip done
2022-03-18 22:27:37,398 DEBUG   HandlerThread:36847 [meta.py:_save_conda():79] save conda
2022-03-18 22:27:39,848 DEBUG   HandlerThread:36847 [meta.py:_save_conda():89] save conda done
2022-03-18 22:27:39,848 DEBUG   HandlerThread:36847 [meta.py:probe():252] probe done
2022-03-18 22:33:13,519 WARNING MainThread:36847 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-03-18 22:33:14,660 WARNING MainThread:36847 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-03-18 22:33:14,661 ERROR   MainThread:36847 [internal.py:wandb_internal():149] Internal process interrupted.
2022-03-18 22:33:15,275 INFO    WriterThread:36847 [datastore.py:close():281] close: /mnt/disk1/dungnt-vaipe/federated-learning-dqn/wandb/offline-run-20220318_222736-23ccjkyr/run-23ccjkyr.wandb
2022-03-18 22:33:15,310 INFO    HandlerThread:36847 [handler.py:finish():731] shutting down handler
2022-03-18 22:33:15,540 INFO    SenderThread:36847 [sender.py:finish():1070] shutting down sender
2022-03-18 22:33:15,542 INFO    MainThread:36847 [internal.py:handle_exit():77] Internal process exited
